services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: mault_toy_app
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
